name: CI

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
      - doc/**

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEBIAN_FRONTEND: noninteractive

    container:
      image: ${{ matrix.docker_image }}

    strategy:
      matrix:
        include:
          - docker_image: ubuntu:20.04
          - docker_image: ubuntu:22.04
          - docker_image: ubuntu:24.04

    steps:

      - name: install sudo
        run: |
          apt update
          apt install -y sudo

      - uses: actions/checkout@v4

      - name: setup
        run: |
          $GITHUB_WORKSPACE/doc/setup.sh

      - name: install
        run: |
          $GITHUB_WORKSPACE/doc/install.sh
