name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
      - '!doc/**/*.sh'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ubuntu_version:
          - "20.04"
          - "22.04"
          - "24.04"
          - "26.04"

    steps:

      - uses: jlumbroso/free-disk-space@v1.3.1

      - uses: actions/checkout@v6

      - name: run "setup" and "install"
        run: >
          docker run
          --env DEBIAN_FRONTEND="noninteractive"
          --volume /home/runner/work/:/home/runner/work/
          ubuntu:${{ matrix.ubuntu_version }}
          /bin/sh -c "$GITHUB_WORKSPACE/doc/setup.sh; $GITHUB_WORKSPACE/doc/install.sh;"
